env:
  global:
    # encrypted COVERITY_SCAN_TOKEN
    - secure: "GZW9ij3PBUPLp4ksM5hcjoQUk5oPrI2Y90kQZA5ZEypPtodhKMiD+T+BDX3UTOfwSWUACDajqMlc6AYwbxrcIqPd6u4eNld3LQ7nAX4pF3i86C59A+xQP54+ezDDGA+HhKQQZIW4O7VP0uj0GbWk9sF8mBrFtnSoKgbXn+y7FcE="

sudo: required

language: c

addons:
  coverity_scan:
    project:
      name: "performancecopilot/pcp"
      description: "Performance Co-Pilot is a system performance analysis toolkit."
    #notification_email: pcp+int+458+579837958761052551@groups.io - temporarily disabled (again) due to coverity server failure
    notification_email: nathans@redhat.com
    build_command_prepend: "./configure"
    build_command: "make"
    branch_pattern: master

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -qq update

script:
  - /bin/true
